url: "https://gorka.io"
baseurl: ""
title: "Gorka López de Torre"
subtitle: "Consultoría de Software"
plugins:
  - jekyll-postcss
postcss:
  cache: false
defaults:
  - scope:
      path: "assets/images"
    values:
      image: true
